"use client";
import { useState } from "react";

const services=["الإنشاءات والمباني","الهندسة والتصاميم","البنية التحتية","تجهيز المشاعر المقدسة"];
const projects=["تجهيزات المشاعر المقدسة","مجمع الإعاشة المركزي","الفلل السكنية والدوبلكس"];

export default function Home(){
 const [menu,setMenu]=useState(false); const [sent,setSent]=useState(false);
 return <main>
  <div className="topline"><span>رواد التعمير والتنمية</span><span>مكة المكرمة والمشاعر المقدسة</span><span>خبرة تمتد منذ 2007م</span></div>
  <header className="nav"><a className="brand" href="#top"><span className="brand-mark"><svg viewBox="0 0 24 28" aria-hidden="true"><path d="M3 25V8l9-5 9 5v17M7 25V12h10v13M3 25h18M9 16h2m2 0h2m-4 4h2m2 0h2"/></svg></span><span><b>رواد التعمير</b><small>والتنمية · ROWAD CONTRACTING</small></span></a><button className="menu-btn" onClick={()=>setMenu(!menu)}>☰</button><nav className={menu?"open":""}><a href="#about">من نحن</a><a href="#services">خدماتنا</a><a href="#projects">مشاريعنا</a><a href="#values">قيمنا</a><a className="nav-cta" href="#contact">تواصل معنا <span>←</span></a></nav></header>
  <section id="top" className="hero"><div className="hero-grid"/><div className="container hero-inner"><div className="hero-copy"><p className="eyebrow"><span/> نبني بثقة منذ 2007</p><h1>نحوّل الأفكار<br/><em>إلى واقعٍ يُبنى عليه</em></h1><p className="lead">شركة سعودية متخصصة في المقاولات والإنشاءات وتجهيز المشاريع، نضع خبرتنا بين أيديكم لنصنع قيمة تدوم.</p><div className="actions"><a className="button primary" href="#projects">اكتشف مشاريعنا <span>←</span></a><a className="button ghost" href="#about">تعرف علينا</a></div></div><div className="hero-visual"><div className="blueprint-card"><img src="/images/rowad-hero.png" alt="مشروع معماري في مكة المكرمة"/><div className="blueprint-overlay"/><span className="vertical-label">BUILT WITH PURPOSE</span><div className="blueprint-caption"><b>رؤية واضحة.</b><br/>تنفيذ دقيق.</div></div><div className="hero-stamp">17+<small>عاماً من الخبرة</small></div></div></div><div className="scroll-cue">مرر لاكتشاف المزيد <span>↓</span></div></section>
  <section className="trust"><div className="container trust-row"><div><b>نُنجز ما نعد به</b><span>شريككم في كل مرحلة من مراحل المشروع</span></div>{[["+17","عاماً من الخبرة"],["+50","مشروعاً منجزاً"],["3","قطاعات رئيسية"],["100%","التزام بالجودة"]].map(x=><div className="trust-stat" key={x[1]}><strong>{x[0]}</strong><span>{x[1]}</span></div>)}</div></section>
  <section id="about" className="section about"><div className="container two-col"><div><p className="eyebrow">01 · من نحن</p><h2>نصنع الفرق<br/><em>بخبرة تُرى</em></h2></div><div className="about-text"><p className="large">منذ انطلاقتنا عام 2007، ونحن نعمل على بناء شراكات ومشاريع تترك أثراً حقيقياً في مكة المكرمة والمملكة.</p><p>بدأت رواد التعمير والتنمية كمؤسسة طموحة، ونمت بخطى ثابتة لتصبح شركة معتمدة لدى هيئة المقاولين ومصنفة لدى وزارة البلديات والإسكان. اليوم، نجمع بين الخبرة التنفيذية والرؤية الحديثة لنقدم حلولاً متكاملة في المقاولات والإنشاءات.</p><a className="text-link" href="#values">اكتشف قصتنا <span>←</span></a></div></div></section>
  <section id="services" className="section services"><div className="container"><div className="section-head"><div><p className="eyebrow">02 · ماذا نقدم</p><h2>خبرة متكاملة<br/><em>لكل مشروع</em></h2></div><p>من التخطيط والتصميم إلى التنفيذ والتسليم، نعمل كفريق واحد لنضمن نتيجة تليق بطموحكم.</p></div><div className="service-grid">{services.map((s,i)=><article className="service-card" key={s}><span className="service-no">0{i+1}</span><span className="service-icon">{["⌂","⌁","⌘","✦"][i]}</span><h3>{s}</h3><p>حلول متكاملة بجودة عالية، تنفذ بأيدي خبرات وطنية ووفق أعلى المعايير.</p><a href="#contact">اعرف المزيد <span>←</span></a></article>)}</div></div></section>
  <section id="projects" className="section projects"><div className="container"><div className="section-head"><div><p className="eyebrow">03 · أعمال نفخر بها</p><h2>مشاريع<br/><em>تتحدث عنّا</em></h2></div><a className="text-link" href="#contact">عرض ملف الشركة <span>←</span></a></div><div className="project-grid">{projects.map((p,i)=><article className="project-card" key={p}><div className="project-image"><img src={['/images/rowad-hajj.png','/images/rowad-hero.png','/images/rowad-villas.png'][i]} alt={p}/><div className="project-pattern"/><span className="project-number">0{i+1}</span></div><div className="project-info"><p>{["مشاريع الحج والمواسم","مكة المكرمة","أعمال الإنشاءات"][i]}</p><h3>{p}</h3><span>{["مخيمات VIP ومرافق خدمية متكاملة","مطبخ إعاشة بمساحة 2,650م²","تنفيذ وتسليم وفق أعلى المعايير"][i]}</span></div></article>)}</div></div></section>
  <section id="values" className="values"><div className="container values-inner"><div><p className="eyebrow">04 · لماذا رواد؟</p><h2>قيم ثابتة.<br/><em>نتائج ملموسة.</em></h2></div><div className="value-list">{[["الأمانة","نبني الثقة قبل أن نبني المشروع."],["الجودة","نلتزم بالمواصفات ونرفع سقف التوقعات."],["السرعة","نخطط بدقة لننجز في الوقت."]].map(v=><div key={v[0]}><b>{v[0]}</b><span>{v[1]}</span></div>)}</div></div></section>
  <section id="contact" className="contact"><div className="container contact-inner"><div><p className="eyebrow">05 · لنبدأ معاً</p><h2>لديك مشروع<br/><em>في بالك؟</em></h2><p>أرسل لنا تفاصيله، وسيتواصل معك فريقنا لمناقشة أفضل الحلول.</p><div className="contact-details"><span>مكة المكرمة · المملكة العربية السعودية</span><span>هاتف: 701832288</span></div></div><form onSubmit={e=>{e.preventDefault();setSent(true)}}><label>الاسم الكامل<input required placeholder="اكتب اسمك"/></label><label>البريد الإلكتروني<input required type="email" placeholder="name@company.com"/></label><label>كيف يمكننا مساعدتك؟<textarea required placeholder="نبذة مختصرة عن مشروعك" rows={3}/></label><button className="button primary">{sent?"تم الإرسال بنجاح ✓":"أرسل طلبك"}<span>←</span></button></form></div></section>
  <footer><div className="container footer-row"><a className="brand" href="#top"><span className="brand-mark"><svg viewBox="0 0 24 28" aria-hidden="true"><path d="M3 25V8l9-5 9 5v17M7 25V12h10v13M3 25h18M9 16h2m2 0h2m-4 4h2m2 0h2"/></svg></span><span><b>رواد التعمير</b><small>والتنمية · ROWAD CONTRACTING</small></span></a><span>© 2025 رواد التعمير والتنمية. جميع الحقوق محفوظة.</span><span>مقاولات · إنشاءات · تطوير</span></div></footer>
 </main>
}
